//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 6beeres_ch.rc
//
#define IDR_HTMLTEST                    113
#define IDB_DOWNLOAD                    114
#define IDB_MEDIARES                    115
#define IDB_FLV                         116
#define IDB_SWF                         117
#define IDB_RM                          118
#define IDB_WM                          119
#define IDS_Description                 120
#define IDS_6Bee                        120
#define IDS_CN_STATUSBAR_SETTING        121
#define IDI_PROXY                       139
#define IDI_PROXY_ENABLED               140
#define IDI_IS_HL                       144
#define IDD_IMG_CAPTURE                 146
#define IDD_TIPWND                      149
#define IDI_6BEELOGO                    152
#define IDD_ABOUT6BEEUPLOADER           153
#define IDB_BITMAP_INFOBK               154
#define IDD_WEBCLIP1                    154
#define IDD_ONLINEBOOKMARK              154
#define IDI_IMAGECAP                    155
#define IDI_6BEEDISABLE                156
#define IDI_6BEEUPLOADER                157
#define IDR_SBar                        160
#define IDB_S5                          166
#define IDB_S1                          167
#define IDB_S2                          168
#define IDB_S3                          169
#define IDB_S4                          170
#define IDB_GGPR                        174
#define IDI_IMGCAPTURE                  176
#define IDI_ULTRAICON                   178
#define IDB_TBSEP                       180
#define IDI_FAVEDIT                     181
#define BUTTON_ClientMng                183
#define BUTTON_CLNMNG_CH                184
#define IDB_ULTRABUTTONS                185
#define BUTTON_UPLOAD_CH                186
#define IDB_CLOSE                       187
#define IDB_SEARCHMENU                  188
#define IDB_STATUSBARIMG                189
#define IDB_ULTRAIELOGIN                191
#define IDB_ULTRAIESTATUS               191
#define IDI_ICON2                       193
#define IDI_HSEARCH                     193
#define IDR_MENU                        201
#define IDR_CLIENTMNGMENU               201
#define IDR_TOOLBARMENU                 205
#define IDC_UPLOAD_NOW                  216
#define IDC_WEBCONTENTSNAME             218
#define IDC_WEBCONTENTSDESC             219
#define IDC_WEBCONTENTSTAG              220
#define IDC_IMG_SETTING                 221
#define IDR_SEARCHMENU                  225
#define IDC_WEBCONTENTS_THUMBNAIL       226
#define IDC_TAG_SUGG                    227
#define IDC_MEDIALIST                   227
#define IDC_POPTAG                      228
#define IDC_IMGPREVIEW                  229
#define IDB_COMBOX_CENTER               229
#define IDB_COMBOX_RIGHT                230
#define SELOGO_BKGND                    253
#define ULTRA_IMGS                      255
#define IDB_SEARCH                      256
#define IDB_SEARCH_BKG                  257
#define IDI_LOGINWND                    260
#define IDC_CURSOR_SEARCH_WINDOW        262
#define IDI_UP                          266
#define IDI_DOWN                        267
#define IDI_HLIGHT                      269
#define IDR_HBAR                        301
#define IDC_WEBCONTENTSNAME2            318
#define IDC_SAVE                        1002
#define IDC_ONBM_DESC                   1004
#define IDC_OLBM_DESC                   1004
#define IDC_EXT                         1005
#define IDC_OLBM_SAVE                   1005
#define IDC_ONBM_URL                    1006
#define IDC_OLBM_URL                    1006
#define IDC_OLBM_TAG                    1007
#define IDC_OLBM_NAME                   1008
#define IDC_OLBM_THUMBNAIL              1009
#define IDC_THUMBNAIL_TEXT              1010
#define IDC_SEPRATOR                    1011
#define IDC_SEPERATOR                   1011
#define IDC_SEP_VER                     1012
#define IDC_GROUP                       1013
#define IDC_DESC_SUGG                   1015
#define IDC_STATIC_VER                  1016
#define IDC_PROGRESS1                   1017
#define IDC_PROGRESS                    1017
#define IDC_BUTTON2                     1018
#define ID_X_UPDATE_TOOLBAR             32777
#define ID_X_UNINSTALL_TOOLBAR          32778
#define ID_ABOUT_6BEE_TOOLBAR           32779
#define ID_A_SHOOTAVIDEO                32779
#define ID_X_MY_6BEE_SPACE              32780
#define ID_A_SINGOUT                    32780
#define ID_A_MY6BEESPACE                32781
#define ID_A_UPLOADFILES                32782
#define ID_A_SCREENCAPTURE              32783
#define ID_A_RECORDVOICE                32784
#define ID_A_EXIT                       32785
#define ID_A_SIGNIN                     32787
#define ID_A_EXIT_LOGIN                 32788
#define ID_A_LOGINOUT                   32789
#define ID_A_EXIT32790                  32790
#define ID_SE_GG                        32791
#define ID_SE_BAIDU                     32792
#define ID_SE_YAHOO                     32793
#define ID_X_CONFIG                     32796
#define ID_SE_CLEAR                     32800
#define ID_N_VERY                       32805
#define ID_N_BEFORE                     32806
#define ID_O_KILL                       32807
#define ID_O_DEAD                       32808
#define ID_P_GOD                        32809
#define ID_P_MAN                        32810
#define ID_Y_UPLOADFILES                32813
#define ID_Z_AREACAP                    32815
#define ID_Z_WEBELEMENTSCAPTURE         32818
#define ID_Z_WHOLEWEBPAGECAPTURE        32819
#define ID_M_SAVEENTIREWEBPAGE          32820
#define ID_M_SAVELINKTOCURRENTPAGE      32821
#define ID_M_SAVESELECTEDTEXTANDIMAGES  32822
#define ID_Z_WINDOWCAP                  32823
#define ID_W_CHECKUPDATE                32825
#define ID_W_CUSTOMIZE                  32826
#define ID_W_ABOUT                      32827
#define ID_AA_SETTING                   32828
#define ID_A_LOGINAS                    40002
#define ID_SETTING_SETTING              40003
#define ID_SETTING_ABOUT                40004
#define ID_SETTING_SMARTHISTORY         40005
#define ID_SETTING_MEDIADETECTION       40006
#define ID_SETTING_ADSBLOCK             40007
#define ID_SETTING_IEPROXY              40008
#define ID_SETTING_ANTIVIRUS            40009
#define ID_SETTING_WEBMUTER             40010
#define ID_SETTING_ALEXARANK            40011
#define ID_SETTING_GOOGLEPR             40012
#define ID_MEDIA_SHOWALL                40013
#define ID_MEDIA_REMOVE                 40014
#define ID_MEDIA_SETTING                40015
#define ID_MEDIA_SWF                    40016
#define ID_MEDIA_RM                     40017
#define ID_MEDIA_MP3                    40018
#define ID_MEDIA_WMV                    40019
#define ID_MEDIA_WMA                    40020
#define ID_MEDIA_AVI                    40021
#define ID_MEDIA_FLV                    40022
#define ID_MEDIA_HELP                   40023
#define ID_MEDIA_HISTORY                40024
#define ID_ALEXA_SITEOVERVIEW           40025
#define ID_ALEXA_TRAFFICDETAILS         40026
#define ID_ALEXA_RELATEDLINKS           40027
#define ID_ANTIVIRUS                    40028
#define ID_ANTIVIRUS_MORNITORPROCESS    40029
#define ID_ANTIVIRUS_MORNITORREGISTRY   40030
#define ID_ANTIVIRUS_MORNITORSTARTUPSETTING 40031
#define ID_ANTIVIRUS_SETTING            40032
#define ID_ALEXA_CACHEDPAGE             40033
#define ID_ANTIVIRUS_MORNITORHOMEPAGE   40034
#define ID_M_SAVEWEBELEMENTASHTML       40035
#define ID_Menu                         40036
#define ID_M_SAVEWEBELEMENTASTEXT       40037
#define ID_A_AUTOLOGIN                  40038
#define ID_Menu40040                    40040
#define ID_SETTING_WEBSOUNDREC          40041
#define ID_Z_CAPTURESETTING             40042
#define ID_O_SAVETHISPAGE               40043
#define ID_O_SYNCHRONIZE_UP             40046
#define ID_O_SYNCHRONIZE_DOWN           40048
#define ID_O_MANAGEMYONLINEBOOKMARK     40049
#define ID_O_MANAGEOLBM                 40050
#define ID_Y                            40051
#define ID_SETTING_CHECKUPDATES         40052
#define ID_SETTING_UNINSTALLTOOLBAR     40053
#define ID_SETTING_UNINSTALL            40054
#define ID_X_SETTING                    40055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         40056
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
