#ifndef _INCLUDE_COPYDATAMSG_
#define _INCLUDE_COPYDATAMSG_


#define CPYDATA_HTMLEDITOR_TO_PROGRESSDLG         1

#define CPYDATA_UUTOOLBAR_TO_CIMGCAPWND_WHOLEPAGE 12
#define CPYDATA_UUTOOLBAR_TO_CIMGCAPWND_WEBELE    13

#define CPYDATA_UUTOOLBAR_TO_CIMGCAPWND_WINDOW    15
#define CPYDATA_UPLOAD_2_UPLOAD                   16
#define CPYDATA_UPLOAD_2_UPLOAD_DIRECT            17


#define CPYDATA_LOGIN  100
#define CPYDATA_LOGOUT 101

#define CPYDATA_MOUSEDLL_TO_STATUSBAR 1000

#define CPYDATA_DOWNLOADIEFAV_OK    2000
#define CPYDATA_DOWNLOADIEFAV_START 2001
#define CPYDATA_UPLOADIEFAV_OK      2002
#define CPYDATA_UPLOADIEFAV_START   2003
#define CPYDATA_FILEUPLOAD_OK       2004
#define CPYDATA_FILEUPLOAD_START    2005
#define CPYDATA_SAVEOLBM_OK         2006
#define CPYDATA_SAVEOLBM_START      2007

#define CPYDATA_DATATRANSFER_TERM 2008

#define CPYDATA_UPLOADBUSY_STOP     2100
#define CPYDATA_DOWNLOADBUSY_STOP   2101


#endif